# Generated by Django 3.2 on 2021-04-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(max_length=400)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_comments', to='todo.todo')),
            ],
        ),
    ]
